control_tower_ip = 'http://192.168.2.193:5001'
time_before_delete_towers = 20
threat_value = 'uav'
kafka_topic_name = 'watchtower'
clf_model_path = 'models/smalluav_v4_svm_filter_banks_clf_0-4sec.pkl'
recording_time = 2
chunk_size = 0.4
number_of_saved_noises = 50
feature_type = 'filter_banks'
logging_enabled = False  # For enabling logging in the log file
log_dev_enabled = False  # For enabling printing intensity and deviation. Used to determine max range
